#!/usr/bin/env python3
"""Write the site's own indexes from the pages themselves (Run 37).

    python3 tools/site-index.py            # write them
    python3 tools/site-index.py --check    # change nothing, exit 1 if stale

assets/js/pb-glossary.js: the jargon buster's entries, word for word. For each
entry, its name as the buster's own index writes it, the first paragraph under
its heading, the anchor on glossary.html, and the phrasings that count as a use
of it on another page: the name and the initialism in brackets after it, each
with a plural. assets/js/pb-terms.js reads it to put the definition beside the
first use of each term on a page (item 2). Nothing here is written by hand
except the two tables below, and each says why.

The buster is the only source: an entry changed there changes here on the
next run, and tests/build.test.py runs --check, so a page and its
index cannot disagree for longer than one commit.
"""
import html
import json
import os
import re
import sys
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLOSSARY = 'glossary.html'
GLOSSARY_JS = 'assets/js/pb-glossary.js'

# Entries that never become a definition in running text. "Pension" is the
# subject of every page on the site: marking its first use would put a
# definition on almost every page's first paragraph and say nothing.
NO_TIP = {'pension'}

# Where the buster's own name is not a phrase anyone writes in running text,
# the phrasing that is. "Fund / investment growth" is one entry for two words;
# "fund" alone is far too common to mark.
PHRASES = {'fund-investment-growth': ['investment growth']}


class _Text(HTMLParser):
    """The text of a fragment, entities decoded, tags dropped."""

    def __init__(self):
        HTMLParser.__init__(self, convert_charrefs=True)
        self.out = []

    def handle_data(self, d):
        self.out.append(d)


def text(fragment):
    p = _Text()
    p.feed(re.sub(r'<br\s*/?>', ' ', fragment))
    p.close()
    return re.sub(r'\s+', ' ', ''.join(p.out)).strip()


def read(rel, root=ROOT):
    with open(os.path.join(root, rel), encoding='utf-8') as f:
        return f.read()


def glossary_entries(src):
    """[(id, name, first paragraph)] in the buster's order. The name is the
    buster's index row for the entry ("Additional Voluntary Contribution
    (AVC)"), which is how the site writes a term out in full."""
    index = re.search(r'<div class="pb-tix" role="navigation" aria-label="Terms on this page">\s*<ul>(.*?)</ul>', src, re.S)
    if not index:
        raise ValueError('glossary.html: the index of terms is missing')
    names = [(a, text(n)) for a, n in re.findall(r'<li><a href="#([a-z0-9-]+)">(.*?)</a></li>', index.group(1))]
    out = []
    for gid, name in names:
        m = re.search(r'<div class="gterm" id="%s"><h2>.*?</h2>\s*<p\b[^>]*>(.*?)</p>' % re.escape(gid), src, re.S)
        if not m:
            raise ValueError('glossary.html: no entry, or no first paragraph, for #%s' % gid)
        out.append((gid, name, text(m.group(1))))
    return out


def phrasings(gid, name):
    """The phrasings that count as a use of the entry, each a (pattern,
    case-sensitive) pair: an initialism must be written in capitals, a name in
    any case. Longest first, so "Personal Retirement Savings Account" wins
    over nothing shorter inside it."""
    if gid in PHRASES:
        pats = [(p, False) for p in PHRASES[gid]]
    else:
        m = re.match(r'^(.*?)\s*\(([A-Z]{2,})\)$', name)
        pats = [(m.group(1), False), (m.group(2), True)] if m else [(name, False)]
    return sorted(pats, key=lambda p: -len(p[0]))


def glossary_js(root=ROOT):
    return glossary_js_from(read(GLOSSARY, root))


def glossary_js_from(src):
    entries = []
    for gid, name, first in glossary_entries(src):
        entries.append({'id': gid, 'name': name, 'def': first,
                        'tip': gid not in NO_TIP,
                        'pats': [[p, cs] for p, cs in phrasings(gid, name)]})
    body = json.dumps(entries, ensure_ascii=True, indent=1)
    return ('/* GENERATED by tools/site-index.py from glossary.html: do not edit here.\n'
            '   Each entry of the jargon buster, word for word: its name as the\n'
            '   buster\'s index writes it, the first paragraph under its heading,\n'
            '   and the phrasings that count as a use of it elsewhere, each\n'
            '   [pattern, case-sensitive]. Read by assets/js/pb-terms.js. */\n'
            'window.PBGlossary = ' + body + ';\n'
            '/* pb-terms.js may have arrived first: start it now that the words are here */\n'
            'if (window.PBTermsBoot) { window.PBTermsBoot(); }\n')


OUTPUTS = ((GLOSSARY_JS, glossary_js),)


def main(argv):
    check = '--check' in argv
    stale = []
    for rel, make in OUTPUTS:
        want = make()
        path = os.path.join(ROOT, rel)
        have = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if have != want:
            stale.append(rel)
            if not check:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(want)
    for rel in stale:
        print('   %-32s %s' % (rel, 'is stale' if check else 'written'))
    if check and stale:
        sys.exit('--check: run python3 tools/site-index.py')
    if not stale:
        print('site indexes up to date')


if __name__ == '__main__':
    main(sys.argv[1:])
