#!/usr/bin/env python3
"""Write the site's own indexes from the pages themselves (Run 37).

    python3 tools/site-index.py            # write them
    python3 tools/site-index.py --check    # change nothing, exit 1 if stale

assets/js/pb-glossary.js: the jargon buster's entries, word for word. For each
entry, its name as the buster's own index writes it, the first paragraph under
its heading, the anchor on glossary.html, and the phrasings that count as a use
of it on another page: the name and the initialism in brackets after it, each
with a plural. assets/js/pb-terms.js reads it to put the definition beside the
first use of each term on a page (item 2). Nothing here is written by hand
except the two tables below, and each says why.

assets/js/pb-search-index.js: every live page (tracked, at the root, not held
back with noindex) by its title, its description, its main heading and the
headings of its sections, and every entry of the buster by its name and first
paragraph. assets/js/pb-search.js loads it the first time a reader opens the
search (item 3), so a page that is never searched never fetches it. A section
with an id is its own place to land; one without sends the reader to its page.

The pages and the buster are the only sources: a page changed there changes
here on the next run, and tests/build.test.py runs --check, so a page and its
index cannot disagree for longer than one commit.
"""
import html
import json
import os
import re
import subprocess
import sys
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLOSSARY = 'glossary.html'
GLOSSARY_JS = 'assets/js/pb-glossary.js'
SEARCH_JS = 'assets/js/pb-search-index.js'
NOINDEX = '<meta name="robots" content="noindex">'
SUFFIX = ', Pensionbuddy'

# Entries that never become a definition in running text. "Pension" is the
# subject of every page on the site: marking its first use would put a
# definition on almost every page's first paragraph and say nothing.
NO_TIP = {'pension'}

# Where the buster's own name is not a phrase anyone writes in running text,
# the phrasing that is. "Fund / investment growth" is one entry for two words;
# "fund" alone is far too common to mark.
PHRASES = {'fund-investment-growth': ['investment growth']}


class _Text(HTMLParser):
    """The text of a fragment, entities decoded, tags dropped."""

    def __init__(self):
        HTMLParser.__init__(self, convert_charrefs=True)
        self.out = []

    def handle_data(self, d):
        self.out.append(d)


def text(fragment):
    p = _Text()
    p.feed(re.sub(r'<br\s*/?>', ' ', fragment))
    p.close()
    return re.sub(r'\s+', ' ', ''.join(p.out)).strip()


def read(rel, root=ROOT):
    with open(os.path.join(root, rel), encoding='utf-8') as f:
        return f.read()


def glossary_entries(src):
    """[(id, name, first paragraph)] in the buster's order. The name is the
    buster's index row for the entry ("Additional Voluntary Contribution
    (AVC)"), which is how the site writes a term out in full."""
    index = re.search(r'<div class="pb-tix" role="navigation" aria-label="Terms on this page">\s*<ul>(.*?)</ul>', src, re.S)
    if not index:
        raise ValueError('glossary.html: the index of terms is missing')
    names = [(a, text(n)) for a, n in re.findall(r'<li><a href="#([a-z0-9-]+)">(.*?)</a></li>', index.group(1))]
    out = []
    for gid, name in names:
        m = re.search(r'<div class="gterm" id="%s"><h2>.*?</h2>\s*<p\b[^>]*>(.*?)</p>' % re.escape(gid), src, re.S)
        if not m:
            raise ValueError('glossary.html: no entry, or no first paragraph, for #%s' % gid)
        out.append((gid, name, text(m.group(1))))
    return out


def phrasings(gid, name):
    """The phrasings that count as a use of the entry, each a (pattern,
    case-sensitive) pair: an initialism must be written in capitals, a name in
    any case. Longest first, so "Personal Retirement Savings Account" wins
    over nothing shorter inside it."""
    if gid in PHRASES:
        pats = [(p, False) for p in PHRASES[gid]]
    else:
        m = re.match(r'^(.*?)\s*\(([A-Z]{2,})\)$', name)
        pats = [(m.group(1), False), (m.group(2), True)] if m else [(name, False)]
    return sorted(pats, key=lambda p: -len(p[0]))


def glossary_js(root=ROOT):
    return glossary_js_from(read(GLOSSARY, root))


def glossary_js_from(src):
    entries = []
    for gid, name, first in glossary_entries(src):
        entries.append({'id': gid, 'name': name, 'def': first,
                        'tip': gid not in NO_TIP,
                        'pats': [[p, cs] for p, cs in phrasings(gid, name)]})
    body = json.dumps(entries, ensure_ascii=True, indent=1)
    return ('/* GENERATED by tools/site-index.py from glossary.html: do not edit here.\n'
            '   Each entry of the jargon buster, word for word: its name as the\n'
            '   buster\'s index writes it, the first paragraph under its heading,\n'
            '   and the phrasings that count as a use of it elsewhere, each\n'
            '   [pattern, case-sensitive]. Read by assets/js/pb-terms.js. */\n'
            'window.PBGlossary = ' + body + ';\n'
            '/* pb-terms.js may have arrived first: start it now that the words are here */\n'
            'if (window.PBTermsBoot) { window.PBTermsBoot(); }\n')


def live_pages(root=ROOT):
    """The pages a reader can land on: tracked html at the root, not held back."""
    try:
        ls = subprocess.run(['git', 'ls-files', '*.html'], cwd=root, capture_output=True, text=True).stdout.split()
    except OSError:
        ls = []
    names = [n for n in ls if '/' not in n] or sorted(f for f in os.listdir(root) if f.endswith('.html'))
    return sorted(n for n in names if NOINDEX not in read(n, root))


def _attr(tag, name):
    m = re.search(r'\b%s="([^"]*)"' % name, tag)
    return html.unescape(m.group(1)) if m else None


def page_record(name, src):
    """One page: where it is, its title less the site's name, its description,
    its main heading, and each section heading in <main>, with an anchor when
    the heading or the block it heads carries an id."""
    title = text(re.search(r'<title>(.*?)</title>', src, re.S).group(1))
    if title.endswith(SUFFIX):
        title = title[:-len(SUFFIX)]
    desc = _attr(re.search(r'<meta name="description"[^>]*>', src).group(0), 'content') or ''
    i, j = src.find('<main'), src.find('</main>')
    main = re.sub(r'<script\b.*?</script>|<style\b.*?</style>|<noscript\b.*?</noscript>', '', src[i:j], flags=re.S)
    h1 = re.search(r'<h1\b[^>]*>(.*?)</h1>', main, re.S)
    secs = []
    for m in re.finditer(r'<h2\b([^>]*)>(.*?)</h2>', main, re.S):
        words = text(m.group(2))
        hid = _attr(m.group(1), 'id')
        if not hid:
            # the <section> the heading is in, when that carries an id: the
            # last one opened before it, with no section closed in between
            before = main[:m.start()]
            o = [x for x in re.finditer(r'<section\b[^>]*\bid="([^"]+)"[^>]*>', before)]
            if o and '</section>' not in before[o[-1].end():]:
                hid = o[-1].group(1)
        if words and [words, hid] not in secs:
            secs.append([words, hid or ''])
    return {'u': name, 't': title, 'd': text(desc), 'h': text(h1.group(1)) if h1 else '', 's': secs}


def search_js(root=ROOT):
    return search_js_from(dict((n, read(n, root)) for n in live_pages(root)), read(GLOSSARY, root))


def search_js_from(sources, glossary_src):
    """The index from pages given as {name: html}; held pages are left out
    here as well as by live_pages(), so a caller cannot slip one in."""
    pages = [page_record(n, sources[n]) for n in sorted(sources) if NOINDEX not in sources[n]]
    for p in pages:
        if p['u'] == GLOSSARY:
            p['s'] = []    # its sections are its entries, indexed below as terms
    terms = [{'u': 'glossary.html#' + gid, 't': name, 'd': first}
             for gid, name, first in glossary_entries(glossary_src)]
    body = json.dumps({'pages': pages, 'terms': terms}, ensure_ascii=True, separators=(',', ':'))
    return ('/* GENERATED by tools/site-index.py from the live pages and glossary.html:\n'
            '   do not edit here. Loaded by assets/js/pb-search.js the first time a\n'
            '   reader opens the search. */\n'
            'window.PBSearchIndex = ' + body + ';\n'
            'if (window.PBSearchReady) { window.PBSearchReady(); }\n')


OUTPUTS = ((GLOSSARY_JS, glossary_js), (SEARCH_JS, search_js))


def main(argv):
    check = '--check' in argv
    stale = []
    for rel, make in OUTPUTS:
        want = make()
        path = os.path.join(ROOT, rel)
        have = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if have != want:
            stale.append(rel)
            if not check:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(want)
    for rel in stale:
        print('   %-32s %s' % (rel, 'is stale' if check else 'written'))
    if check and stale:
        sys.exit('--check: run python3 tools/site-index.py')
    if not stale:
        print('site indexes up to date')


if __name__ == '__main__':
    main(sys.argv[1:])
